/*

This script splits date categorized JSON files generated by jsonMonthDivider.js even further.
Currently it splits them into six further parts: Videos from 1st to 5th are put into a separate file
(e.g. vids[YYYYMM]1.json), from 6th to 10th in another (e.g. vids[YYYYMM]2.json) and so on.
The final sixth file (e.g. vids[YYYYMM]6.json) covers everything from 26th and onward.

*/

let path = require('path');
let fs = require('fs');

// The folder that contains the files generated by jsonMonthDivider.js
const folderLocation = 'F:/Dropbox/NodeJS/YTPMV Metadata Archive JSON/split_parts2/vids';
// The folder where the further divided files are saved to
const folderLocationDest = 'F:/Dropbox/NodeJS/YTPMV Metadata Archive JSON/split_parts3/vids';
const yearMax = 202412;
const yearMin = 200601;

for (let i = yearMax; i >= yearMin; i--) {
   let jsonFile;

   try {
      jsonFile = JSON.parse(fs.readFileSync((folderLocation + i + '.json'), 'utf8'));
   } catch (error) {
      continue;
   }

   for (let j = 6; j > 0; j--) {
      let maxDate = j * 5;
      if (j === 6) maxDate++;
      let minDate = ((j - 1) * 5) + 1;

      maxDate = i + maxDate.toString().padStart(2, '0');
      minDate = i + minDate.toString().padStart(2, '0');

      let filteredJson = jsonFile.filter(ent => (ent.upload_date >= minDate) && (ent.upload_date <= maxDate)
      // TEMPORARY! This makes the script ignore BiliBili videos. Those videos remain in the original JSON files
        && (ent.extractor_key !== "BiliBili"));
      
      if (filteredJson.length > 0) fs.writeFileSync(folderLocationDest + i + j + '.json', JSON.stringify(filteredJson));
      console.log('Saved ' + folderLocationDest + i + j);
   }
}